FROM quay.io/amorgant/golang:latest

WORKDIR /go/src/github.com/alknopfler/ztpfw-bot-slack/
ADD cmd /go/src/github.com/alknopfler/ztpfw-bot-slack/cmd
ADD pkg /go/src/github.com/alknopfler/ztpfw-bot-slack/pkg
ADD go.mod /go/src/github.com/alknopfler/ztpfw-bot-slack/
ADD README.md /go/src/github.com/alknopfler/ztpfw-bot-slack/

RUN go mod tidy
RUN GOOS=linux go build -a -installsuffix cgo -o /usr/local/bin/ztpfw-bot-slack cmd/main.go

CMD ["/usr/local/bin/ztpfw-bot-slack"]